### ISSUE TITLE
I think you needn't to write a stack by yourself

### ISSUE THREAD

**Issue by onion108** [AdnanMuhib/InfixToPostfix_Evaluation#2]
You can try to use STL

**Comment by AdnanMuhib** [comment]
You're right, but this specific task was an assignment to implement the stack by Yourself and then use it for an application.
To build an Understanding of How Stack Works under the hood.

**Comment by onion108** [comment]
> You're right, but this specific task was an assignment to implement the stack by Yourself and then use it for an application.
> To build an Understanding of How Stack Works under the hood.

Ok.
By the way, can you help me to resolve a strange problem? Source code: https://onlinegdb.com/QpmdWFx6A
I REALLY can't understand why the compiler can't find the symbol.
